### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by eduardo-ballesteros** [albaosanti/outlook-addin-dragdrop-watcher#1]
When synchronizing a folder's rules, can the program do as follows:

* Eliminate the confirmation when you go to farcap plugin -> Synchronise
* Add a dropdown to the Synchronise screen to ask for:
* How many months to scan through (1 month, 2, months, 3 months up to a year and all emails).  A current user has 156000 emails in a folder so we don't want to scan them all because that will take too long.
* Show the statistics of the current rule senders (say the rule currently has 100 senders) and by scanning the messages show that it will have X number of senders in the rule (here the code scans the sender email addresses, finds the unique ones,) and gets them ready to save into the rule if the user accepts.
* The screen should then have statistics of how many senders are in the current rule and after scanning, show how many senders will be added to the rule.  When the rule is saved, it should remove all existing senders and add the ones coming from the folder.

![image](https://user-images.githubusercontent.com/8726779/124700587-8eefea00-df1f-11eb-92bc-5490157d5da3.png)

As far as optimization, we should scan the messages using the GetTable mechanism.  See below:

    private void ProcessEmails()
    {
      var stopWatch = System.Diagnostics.Stopwatch.StartNew();

      var items = _folder.GetTable();
      var count = items.GetRowCount();
      var senders = new List<SenderData>();
      var uniqueEmails = new HashSet<string>();

      items.Columns.RemoveAll();
      items.Columns.Add("SenderName");
      items.Columns.Add("SenderEmailAddress");
      items.Columns.Add("SenderEmailType");

      for (int index = 0; index < count; index++)
      {
        var mailItem = (Outlook.Row)items.GetNextRow();
        var name = (string)mailItem["SenderName"];
        var senderType = (string)mailItem["SenderEmailType"];
        var emailAddress = senderType == "EX" ? GetEmailAddressForExchangeServer((string)mailItem["SenderEmailAddress"]) : (string)mailItem["SenderEmailAddress"];

        labelStatus.Content = $"Sender {name} <{emailAddress}> {index} of {count}";

        if (!string.IsNullOrEmpty(emailAddress) && uniqueEmails.Add(emailAddress))
          senders.Add(new SenderData { Name = name, EmailAddress = emailAddress, FolderName = _folder.Name, SenderEmailType = senderType });
      }

      gridSenders.ItemsSource = senders.ToHashSet();

      stopWatch.Stop();
      
      labelStatus.Content = $"Getting unique emails in folder took: {stopWatch.ElapsedMilliseconds}ms";
    }

**Comment by eduardo-ballesteros** [comment]
One issue that I am experiencing is with deleting mail.   When you delete something, it may be doing something with the mail item where it starts ignoring the command.  I selected multiple emails to delete, then hit the delete button and then nothing happened.  If I remove the plugin, it works as expected.  Can you test and add some logic to not do anything when deleting items?

**Comment by albaosanti** [comment]
> One issue that I am experiencing is with deleting mail. When you delete something, it may be doing something with the mail item where it starts ignoring the command. I selected multiple emails to delete, then hit the delete button and then nothing happened. If I remove the plugin, it works as expected. Can you test and add some logic to not do anything when deleting items?

Okay, I'll check on this. It has to skip the ruling process when the target folder is "Deleted Items".
